# Generated by Django 5.1.1 on 2024-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_brand_shoe_shoestyle_style_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='size',
            field=models.IntegerField(default=7),
        ),
    ]
