# Generated by Django 5.1.1 on 2024-09-26 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_style_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.brand'),
        ),
    ]
